/*
 * @lc app=leetcode id=121 lang=java
 *
 * [121] Best Time to Buy and Sell Stock
 */

// @lc code=start
class Solution {
    public int maxProfit(int[] prices) {
        //clarification:
        //If we choose one day, the profit is generated by a higher price later and the goal here is to maximize the profit

        //Edge case
        //price = [1] -> 0
        //price = [9, 8, 7, 6, 5] -> 0
        //price = [3,3,3,3,3] -> 0

        //solution
        int ans = 0;
        int min = Integer.MAX_VALUE;
        for(int price : prices){
            if(min == Integer.MAX_VALUE){
                min = price;
            }
            if(price > min){
                ans = Math.max(ans, price - min);
            }else{
                min = price;
            }

        }
        return ans;
        //algo philosophy here: avoid unneeded calculations
    }
}
// @lc code=end

